opensearch:
  uris: ${OPEN_SEARCH_URI}
  username: ${OPEN_SEARCH_USERNAME}
  password: ${OPEN_SEARCH_PASSWORD}
  page-size: ${OPEN_SEARCH_PAGE_SIZE:20}

spring:
  jackson:
    serialization:
      indent-output: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
      base-path: /internal

kodeverk:
  spraak:
    url: ${KODEVERK_SPRAAK_URL}

no.nav.security.jwt:
  issuer:
    azuread:
      accepted-audience: ${AZURE_APP_CLIENT_ID}
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}