apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: navno-search-admin-api-alert
  namespace: personbruker
  labels:
    team: personbruker
spec:
  groups:
    - name: navno-search-admin-api-alert
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="navno-search-admin-api"} == 0
          for: 2m
          annotations:
            summary: "App navno-search-admin-api er nede"
            action: "Sjekk logger/events i kubectl"
          labels:
            severity: danger
            receiver_reference: team-navno-backend-alerts
            alert_type: custom
        - alert: høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(log_messages_errors{app="navno-search-admin-api",level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(log_messages_total{app="navno-search-admin-api"}[3m]))) > 10
          for: 3m
          annotations:
            summary: "App navno-search-admin-api har høy feilrate i logger"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: warning
            receiver_reference: team-navno-backend-alerts
            alert_type: custom
        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: (100 * (sum by (backend) (rate(http_server_requests_seconds_count {status=~"^5\\d\\d", namespace="personbruker", app="navno-search-admin-api"}[3m])) / sum by (backend) (rate(http_server_requests_seconds_count {namespace="personbruker", app="navno-search-admin-api"}[3m])))) > 1
          for: 3m
          annotations:
            summary: "App navno-search-admin-api returnerer en høy andel 5xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: danger
            receiver_reference: team-navno-backend-alerts
            alert_type: custom
        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: (100 * (sum by (backend) (rate(http_server_requests_seconds_count {status=~"^4\\d\\d", namespace="personbruker", app="navno-search-admin-api"}[3m])) / sum by (backend) (rate(http_server_requests_seconds_count {namespace="personbruker", app="navno-search-admin-api"}[3m])))) > 10
          for: 3m
          annotations:
            summary: "App navno-search-admin-api returnerer en høy andel 4xx-responser"
            action: "Sjekk logger i kibana eller kubectl"
          labels:
            severity: warning
            receiver_reference: team-navno-backend-alerts
            alert_type: custom
