apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: navno-search-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /internal/isReady
    initialDelay: 60
    timeout: 1
  replicas:
    min: { { min-replicas } }
    max: { { max-replicas } }
  openSearch:
    access: readwrite
    instance: navno-search
  ingresses:
  { { #each ingresses}}
      - "{{this}}"
          {{/each } }
  envFrom:
    - secret: navno-search-api-secret
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 384Mi
