apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: navno-search-admin-api
  namespace: personbruker
  labels:
    team: personbruker
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /internal/health
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  openSearch:
    access: admin
    instance: navno-search
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kodeverk-api.nav.no
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  envFrom:
    - secret: navno-search-admin-api-secret
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1536Mi
    requests:
      cpu: 300m
      memory: 768Mi
