apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  labels:
    team: navno
  name: opensearch-navno-navno-search
  namespace: navno
spec:
  plan: {{opensearch-plan}}
  project: {{opensearch-project}}
  userConfig:
    opensearch_version: "2"

---

apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: navno
  name: opensearch-navno-navno-search
  namespace: navno
spec:
  project: {{opensearch-project}}
  integrationType: prometheus
  destinationEndpointId: {{opensearch-endpoint-id}}
  sourceServiceName: opensearch-navno-navno-search
