name: Deploy to prod
on:
  release:
    types: [ released ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and deploy prod
        uses: ./.github/actions/build-and-deploy
        with:
          ENVIRONMENT: prod
          NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}