name: Deploy Opensearch prod
on:
  workflow_dispatch

jobs:
  deploy-opensearch:
    name: Deploy Opensearch instance to cluster
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ./nais/opensearch.yaml
          VARS: ./nais/prod-gcp/personbruker.json